REM You can increase the number of clients by repeating start ExecuteClient.cmd
SET SUBDIR=%~dp0

start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
start %SUBDIR%ConnectionsClerk.cmd
exit
